# Generated by Django 4.2.2 on 2023-06-08 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
            CREATE VIEW short_urls_view AS
                SELECT shortcode,
                       date_created,
                       username,
                       full_url,
                       is_deleted,
                       times_accessed,
                       expiry_time
                FROM   api_shorturl
                       LEFT JOIN api_shorturlstats
                              ON api_shorturl.shortcode = api_shorturlstats.shortcode_id
                       LEFT JOIN auth_user
                              ON api_shorturl.user_id = auth_user.id;                
        """, reverse_sql="""
            DROP VIEW IF EXISTS short_urls_view;
        """)
    ]
